[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "asr-ne-corrector"
version = "0.1.0"
description = "RAG-inspired phonetic correction for Chinese ASR named entities"
authors = [{ name = "OpenAI Assistant" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = [
    "pypinyin>=0.47",
    "panphon>=0.20",
]

[project.urls]
Home = "https://example.com"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"
