[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "asr-postprocessor"
version = "0.1.0"
description = "Phonetic correction utilities for Chinese ASR outputs"
authors = [{name = "Unknown"}]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "epitran>=1.24",
    "panphon>=0.20",
]

[project.urls]
Homepage = "https://example.com/asr-postprocessor"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
