[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rag-asr-correction"
version = "0.1.0"
description = "RAG-inspired post-processing for multilingual ASR outputs using phonetic and tone-aware distances"
readme = "README.md"
authors = [{name = "Unknown"}]
requires-python = ">=3.10"
dependencies = [
    "phonemizer>=3.2",
    "panphon>=0.20",
    "pypinyin>=0.49",
    "abydos @ git+https://github.com/denizberkin/abydos.git"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
]

[project.urls]
Homepage = "https://example.com"

[tool.setuptools.packages.find]
where = ["src"]
