[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "phonetic-corrector"
version = "0.1.0"
description = "Phonetic named-entity correction helpers for Chinese ASR output"
readme = "README.md"
authors = [{name = "App User"}]
license = {text = "MIT"}
requires-python = ">=3.10"
dependencies = [
    "pypinyin>=0.49",
    "panphon>=0.20",
]

[project.urls]
Homepage = "https://example.com/phonetic-corrector"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
