[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "phonetic-rag"
version = "0.1.0"
description = "Phonetic distance utilities for correcting multilingual ASR output"
readme = "README.md"
authors = [
  {name = "ASR Distance Maintainers"}
]
license = {text = "MIT"}
requires-python = ">=3.9"
dependencies = [
  "numpy>=1.22",
  "pypinyin>=0.50",
  "eng-to-ipa>=0.0.2",
  "panphon>=0.20",
  "pyclts>=3.0",
  "abydos @ git+https://github.com/denizberkin/abydos.git",
]

[project.urls]
Homepage = "https://example.com/phonetic-rag"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["phonetic_rag*"]
