[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rag-phonetic-correction"
version = "0.1.0"
description = "Phonetic distance-based correction for Chinese ASR outputs"
authors = [{name = "Your Name"}]
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
dependencies = [
    "pypinyin>=0.49",
    "panphon>=0.20",
    "abydos>=0.5",
]

[project.optional-dependencies]
dev = ["pytest"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"rag_phonetic_correction" = ["py.typed"]

[tool.pytest.ini_options]
addopts = "-ra"
pythonpath = ["src"]
