[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "asr-correction"
version = "0.1.0"
description = "Phonetic post-correction utilities for multilingual ASR outputs"
authors = [{name = "Generated", email = "generated@example.com"}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pypinyin>=0.50",
    "eng_to_ipa>=0.0.2",
    "panphon>=0.20",
    "numpy>=1.23",
    "git+https://github.com/denizberkin/abydos.git",
]

[project.urls]
Homepage = "https://example.com"

[project.optional-dependencies]
test = []

[tool.setuptools.packages.find]
where = ["."]
include = ["asr_correction"]
