[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "asr-corrector"
version = "0.1.0"
description = "Multilingual ASR correction using phonetic distance and knowledge bases"
readme = "README.md"
authors = [{ name = "OpenAI Assistant" }]
license = { text = "MIT" }
requires-python = ">=3.10"
dependencies = [
    "phonemizer>=3.2.1",
    "panphon>=0.20",
    "abydos @ git+https://github.com/denizberkin/abydos.git",
]

[project.optional-dependencies]
test = [
    "pytest>=7.4",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["asr_corrector"]
