[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "asr-phonetic-corrector"
version = "0.1.0"
description = "Phonetic post-correction for Chinese ASR transcripts"
authors = [{name = "OpenAI Assistant"}]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pypinyin>=0.49",
    "panphon>=0.20",
]

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["asr_corrector*"]
