[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rag-phonetic-correction"
version = "0.1.0"
description = "Post-process Chinese ASR output via phonetic retrieval"
readme = "README.md"
authors = [{ name = "AI Assistant" }]
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = [
    "numpy<2",
    "pypinyin>=0.49",
    "panphon>=0.20",
    "abydos>=0.5",
]

[project.urls]
Homepage = "https://example.com/rag-phonetic-correction"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
rag_phonetic_correction = ["py.typed"]
