[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "asr-postproc"
version = "0.1.0"
description = "Phonetic named-entity correction for Chinese ASR transcripts"
readme = "README.md"
authors = [
    { name = "OpenAI Assistant" },
]
requires-python = ">=3.9"
dependencies = [
    "pypinyin>=0.50.0",
    "panphon>=0.20.0",
]

[project.urls]
Homepage = "https://example.com/asr-postproc"

[tool.setuptools.packages.find]
where = ["src"]
