[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "asr-corrector"
version = "0.1.0"
description = "Phonetic distance based post-correction utilities for Chinese ASR outputs"
authors = [{name = "OpenAI Assistant"}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pypinyin>=0.50",
    "panphon>=0.20",
    "nltk>=3.8",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[project.urls]
Homepage = "https://example.com/asr-corrector"

[tool.setuptools.packages.find]
include = ["asr_corrector"]
