[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "asr-corrector"
version = "0.1.0"
description = "Correct Chinese ASR named-entity errors using phonetic similarity."
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "ASR Corrector Maintainers" },
]
dependencies = []

[project.optional-dependencies]
phonetics = [
    "pypinyin>=0.50",
    "panphon>=0.20",
]
test = [
    "pytest>=7",
]

[project.urls]
Homepage = "https://example.com/asr-corrector"

[tool.setuptools.packages.find]
where = ["."]
