[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "asr-corrector"
version = "0.1.0"
description = "Phonetic post-correction utilities for Chinese ASR transcripts"
readme = "README.md"
authors = [
    {name = "OpenAI Assistant"}
]
license = {text = "MIT"}
requires-python = ">=3.9"
dependencies = [
    "pypinyin>=0.50",
    "panphon>=0.20",
    "abydos>=0.5",
    "pyclts>=3.0",
]

[project.optional-dependencies]
lingpy = ["lingpy>=2.6"]

[project.urls]
"Source" = "https://example.com/asr-corrector"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"asr_corrector" = ["py.typed"]
